"""widen primary_position, add player height_cm

Revision ID: 496f72a0604f
Revises: 4f42a8f0cc7b
Create Date: 2026-08-29 20:37:59.071340

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '496f72a0604f'
down_revision: Union[str, Sequence[str], None] = '4f42a8f0cc7b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('player', sa.Column('height_cm', sa.Integer(), nullable=True))
    op.alter_column('player', 'primary_position',
               existing_type=sa.VARCHAR(length=16),
               type_=sa.String(length=64),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('player', 'primary_position',
               existing_type=sa.String(length=64),
               type_=sa.VARCHAR(length=16),
               existing_nullable=True)
    op.drop_column('player', 'height_cm')
    # ### end Alembic commands ###
