"""add player market value and attribute profile

Revision ID: 4f42a8f0cc7b
Revises: 28597282d578
Create Date: 2026-08-29 19:33:51.206502

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '4f42a8f0cc7b'
down_revision: Union[str, Sequence[str], None] = '28597282d578'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('player_attribute_profile',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('player_id', sa.Integer(), nullable=False),
    sa.Column('source', sa.String(length=32), nullable=False),
    sa.Column('comparison_group_key', sa.String(length=64), nullable=False),
    sa.Column('attributes', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('computed_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['player_id'], ['player.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('player_id', 'source', 'comparison_group_key', name='uq_player_attribute_profile')
    )
    op.create_table('player_market_value',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('player_id', sa.Integer(), nullable=False),
    sa.Column('source', sa.String(length=32), nullable=False),
    sa.Column('as_of_date', sa.Date(), nullable=False),
    sa.Column('value_eur', sa.Integer(), nullable=False),
    sa.Column('lower_bound_eur', sa.Integer(), nullable=True),
    sa.Column('upper_bound_eur', sa.Integer(), nullable=True),
    sa.Column('valuation_source', sa.String(length=32), nullable=False),
    sa.Column('club_id_at_valuation', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['club_id_at_valuation'], ['club.id'], ),
    sa.ForeignKeyConstraint(['player_id'], ['player.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('player_id', 'source', 'as_of_date', name='uq_player_market_value')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('player_market_value')
    op.drop_table('player_attribute_profile')
    # ### end Alembic commands ###
